/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ../Sig552.glb --transform
*/

import React, { Suspense, useState } from 'react'
import { useGLTF } from '@react-three/drei'

export function  Sig552({mag,sight,underbarrel}) {

  const { nodes, materials } = useGLTF('https://ac-dev-s3.s3.us-west-1.amazonaws.com/glb/Sig552Updated.glb')
  console.log(nodes.magazine,"nodes")
  console.log(materials,"materials",sight)
  return (
    <group dispose={null}>
      <group position={[-2.15, -2.2, 1.81]} rotation={[0.39, -0.56, 0.13]}>
        <mesh visible={false} geometry={nodes.bolt.geometry} material={materials['Material #6']} position={[-0.01, 0.09, 0.09]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh geometry={nodes.sig552_mobile.geometry} material={materials.sig552_mobile_diffuse} position={[0.01, 0.04, 0]} rotation={[-Math.PI / 2, 0, 0]} />
        <mesh visible={mag == 'sig552_mobile_diffuse'} geometry={nodes.Extended_1.geometry} material={materials['sig552_mobile_diffuse']} position={[0.01, -0.04, 0.05]} rotation={[0, -Math.PI / 2, 0]} scale={0.21} />
        <mesh visible={mag == 'Magazine (2) Short'} geometry={nodes.Short_1.geometry} material={materials['Magazine (2) Short']} position={[0.01, -0.01, 0.04]} rotation={[0, -1.57, 0]} scale={0.26} />
        <mesh visible={mag == 'Magazine (3) Short'} geometry={nodes.Short_2.geometry} material={materials['Magazine (3) Short']} position={[0.01, 0.02, 0.05]} rotation={[0, -Math.PI / 2, 0]} scale={0.26} />
        <mesh visible={mag == 'Magazine (4) Short'} geometry={nodes.Short_3.geometry} material={materials['Magazine (4) Short']} position={[0.01, -0.01, 0.05]} rotation={[0, -Math.PI / 2, 0]} scale={0.26} />
        <mesh visible={mag == 'Magazine (5) Short'} geometry={nodes.Short_4.geometry} material={materials['Magazine (5) Short']} position={[0.02, -0.01, 0.04]} rotation={[0, -Math.PI / 2, 0]} scale={0.26} />
        <mesh visible={mag == 'Magazine (1) Short'} geometry={nodes.Short.geometry} material={materials['Magazine (1) Short']} position={[0.01, 0, 0.05]} rotation={[0, -Math.PI / 2, 0]} scale={0.26} />
        <mesh visible={mag == 'Magazine (2) Standard'} geometry={nodes.Standard_1.geometry} material={materials['Magazine (2) Standard']} position={[0.01, -0.03, 0.05]} rotation={[0, -Math.PI / 2, 0]} scale={0.26} />
        <mesh visible={mag == 'Magazine (3) Standard'} geometry={nodes.Standard_2.geometry} material={materials['Magazine (3) Standard']} position={[0.01, -0.03, 0.06]} rotation={[0, -Math.PI / 2, 0]} scale={[0.26, 0.25, 0.26]} />
        <mesh visible={mag == 'Magazine (4) Standard'} geometry={nodes.Standard_3.geometry} material={materials['Magazine (4) Standard']} position={[0.01, -0.04, 0.07]} rotation={[0, -Math.PI / 2, 0]} scale={0.26} />
        <mesh visible={mag == 'Magazine (5) Standard'} geometry={nodes.Standard_4.geometry} material={materials['Magazine (5) Standard']} position={[0.01, -0.04, 0.07]} rotation={[0, -Math.PI / 2, 0]} scale={0.26} />
        <mesh visible={mag == 'Magazine (1) Standard'} geometry={nodes.Standard.geometry} material={materials['Magazine (1) Standard']} position={[0.01, -0.04, 0.07]} rotation={[0, -Math.PI / 2, 0]} scale={0.26} />
        <group  visible={sight == 'Holographic Sight' } position={[0.01, 0.13, 0.06]} scale={0.24}>
          <mesh geometry={nodes.Holographic_Sight_1.geometry} material={materials['Holographic Sight Body']} />
          <mesh geometry={nodes.Holographic_Sight_2.geometry} material={materials['Holographic Sight Glass']} />
        </group>
        <group visible={sight == 'Optical Sight (1)' } position={[0.01, 0.12, 0.06]} scale={0.23}>
          <mesh geometry={nodes['Optical_Sight_(1)_1'].geometry} material={materials['Optical Sight (1) Body']} />
          <mesh geometry={nodes['Optical_Sight_(1)_2'].geometry} material={materials['Optical Sight (1) Glass']} />
        </group>
        <group visible={sight == 'Optical Sight (2)' } position={[0.01, 0.13, 0.06]} scale={0.23}>
          <mesh geometry={nodes['Optical_Sight_(2)_1'].geometry} material={materials['Optical Sight (2) Body']} />
          <mesh geometry={nodes['Optical_Sight_(2)_2'].geometry} material={materials['Optical Sight (2) Glass']} />
        </group>
        <group visible={sight == 'Optical Sight (3)' } position={[0.01, 0.13, 0.06]} scale={0.23}>
          <mesh geometry={nodes['Optical_Sight_(3)_1'].geometry} material={materials['Optical Sight (3) Body']} />
          <mesh geometry={nodes['Optical_Sight_(3)_2'].geometry} material={materials['Optical Sight (3) Glass']} />
        </group>
        <group visible={sight == 'Reflex Sight (1)' } position={[0.01, 0.12, 0.05]} scale={0.23}>
          <mesh geometry={nodes['Reflex_Sight_(1)_1'].geometry} material={materials['Reflex Sight (1) Body']} />
          <mesh geometry={nodes['Reflex_Sight_(1)_2'].geometry} material={materials['Reflex Sight (1) Glass']} />
        </group>
        <group visible={sight == 'Reflex Sight (2)' } position={[0.01, 0.12, 0.06]} scale={0.23}>
          <mesh geometry={nodes['Reflex_Sight_(2)_1'].geometry} material={materials['Reflex Sight (2) Body']} />
          <mesh geometry={nodes['Reflex_Sight_(2)_2'].geometry} material={materials['Reflex Sight (2) Glass']} />
        </group>
        <group visible={sight == 'Reflex Sight (3)' } position={[0.01, 0.12, 0.06]} scale={0.23}>
          <mesh geometry={nodes['Reflex_Sight_(3)_1'].geometry} material={materials['Reflex Sight (3) Body']} />
          <mesh geometry={nodes['Reflex_Sight_(3)_2'].geometry} material={materials['Reflex Sight (3) Glass']} />
        </group>
        <mesh visible={underbarrel == 'Vertical Grip (1)'} geometry={nodes['Vertical_Grip_(1)'].geometry} material={materials['Vertical Grip (1)']} position={[0.01, 0, 0.17]} scale={0.31} />
        <mesh visible={underbarrel == 'Vertical Grip (2)'} geometry={nodes['Vertical_Grip_(2)'].geometry} material={materials['Vertical Grip (2)']} position={[0.01, 0, 0.17]} scale={0.31} />
        <mesh visible={underbarrel == 'Vertical Grip (3)'} geometry={nodes['Vertical_Grip_(3)'].geometry} material={materials['Vertical Grip (3)']} position={[0.01, 0.01, 0.18]} scale={0.31} />
        <mesh visible={underbarrel == 'Vertical Grip (4)'} geometry={nodes['Vertical_Grip_(4)'].geometry} material={materials['Vertical Grip (4)']} position={[0.01, 0.01, 0.17]} scale={0.31} />
        <mesh visible={underbarrel == 'Vertical Grip (5)'} geometry={nodes['Vertical_Grip_(5)'].geometry} material={materials['Vertical Grip (5)']} position={[0.01, 0.01, 0.17]} scale={0.31} />
        <mesh visible={underbarrel == 'Vertical Grip (6)'} geometry={nodes['Vertical_Grip_(6)'].geometry} material={materials['Vertical Grip (6)']} position={[0.01, 0.01, 0.17]} scale={0.31} />
      </group>
    </group>
  )
}

useGLTF.preload('https://ac-dev-s3.s3.us-west-1.amazonaws.com/glb/Sig552Updated.glb')
