/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./weapon.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

function Weapon(props) {
  const { nodes, materials } = useGLTF('https://ac-dev-s3.s3.us-west-1.amazonaws.com/glb/weapon-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0, 0.26]} rotation={[-Math.PI, -0.52, 0]}>
        <mesh geometry={nodes.Mesh_0002.geometry} material={materials['Material_0.001']} />
        <mesh geometry={nodes.Mesh_0002_1.geometry} material={materials['Material_1.001']} />
        <mesh geometry={nodes.Mesh_0002_2.geometry} material={materials['Material_2.001']} />
        <mesh geometry={nodes.Mesh_0002_3.geometry} material={materials['Material_3.001']} />
        <mesh geometry={nodes.Mesh_0002_4.geometry} material={materials['Material_4.001']} />
        <mesh geometry={nodes.Mesh_0002_5.geometry} material={materials['Material_5.001']} />
        <mesh geometry={nodes.Mesh_0002_6.geometry} material={materials['Material_6.001']} />
        <mesh geometry={nodes.Mesh_0002_7.geometry} material={materials['Material_7.001']} />
        <mesh geometry={nodes.Mesh_0002_8.geometry} material={materials['Material_8.001']} />
        <mesh geometry={nodes.Mesh_0002_9.geometry} material={materials['Material_9.001']} />
        <mesh geometry={nodes.Mesh_0002_10.geometry} material={materials['Material_10.001']} />
        <mesh geometry={nodes.Mesh_0002_11.geometry} material={materials['Material_11.001']} />
        <mesh geometry={nodes.Mesh_0002_12.geometry} material={materials['Material_12.001']} />
        <mesh geometry={nodes.Mesh_0002_13.geometry} material={materials['Material_13.001']} />
        <mesh geometry={nodes.Mesh_0002_14.geometry} material={materials['Material_14.001']} />
        <mesh geometry={nodes.Mesh_0002_15.geometry} material={materials['Material_15.001']} />
        <mesh geometry={nodes.Mesh_0002_16.geometry} material={materials['Material_16.001']} />
        <mesh geometry={nodes.Mesh_0002_17.geometry} material={materials['Material_17.001']} />
        <mesh geometry={nodes.Mesh_0002_18.geometry} material={materials['Material_18.001']} />
        <mesh geometry={nodes.Mesh_0002_19.geometry} material={materials['Material_19.001']} />
        <mesh geometry={nodes.Mesh_0002_20.geometry} material={materials['Material_20.001']} />
        <mesh geometry={nodes.Mesh_0002_21.geometry} material={materials['Material_21.001']} />
        <mesh geometry={nodes.Mesh_0002_22.geometry} material={materials['Material_22.001']} />
        <mesh geometry={nodes.Mesh_0002_23.geometry} material={materials['Material_23.001']} />
        <mesh geometry={nodes.Mesh_0002_24.geometry} material={materials['Material_24.001']} />
        <mesh geometry={nodes.Mesh_0002_25.geometry} material={materials['Material_25.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('https://ac-dev-s3.s3.us-west-1.amazonaws.com/glb/weapon-transformed.glb')

export default Weapon;