/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 SK_Military_Underwear6.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SK_Military_Character6({muzzle}) {
  const { nodes, materials } = useGLTF('https://ac-dev-s3.s3.us-west-1.amazonaws.com/glb/characters/fullModels/SK_Military_Character6-full.glb')
  console.log(nodes,"ani")
  return (
    <group dispose={null}>
      <group position={[1.89, -3.68, 9.74]} rotation={[0, -0.46, 0]}>
        <primitive object={nodes.root} />
        <skinnedMesh visible={muzzle == 'Boots3'} geometry={nodes.Boots3.geometry} material={materials.Boots3_Skin1} skeleton={nodes.Boots3.skeleton} position={[1.31, 0.14, -0.29]} />
        <skinnedMesh geometry={nodes.Boots4.geometry} material={materials.Boots_4_5_skin1} skeleton={nodes.Boots4.skeleton} />
        <skinnedMesh geometry={nodes.Boots5.geometry} material={materials.Boots_4_5_skin1} skeleton={nodes.Boots5.skeleton} />
        <skinnedMesh geometry={nodes.CHR_Male_Foot.geometry} material={materials.Legs1_skin1} skeleton={nodes.CHR_Male_Foot.skeleton} />
        <skinnedMesh geometry={nodes.Holster1_empty.geometry} material={materials.Equip2_skin1} skeleton={nodes.Holster1_empty.skeleton} />
        <skinnedMesh geometry={nodes.Kneepad1_Left.geometry} material={materials.Pants1_Skin1} skeleton={nodes.Kneepad1_Left.skeleton} />
        <skinnedMesh geometry={nodes.Kneepad1_Right.geometry} material={materials.Pants1_Skin1} skeleton={nodes.Kneepad1_Right.skeleton} />
        <skinnedMesh geometry={nodes.Pants1.geometry} material={materials.Pants1_Skin1} skeleton={nodes.Pants1.skeleton} position={[9.29, -0.94, 0.02]} />
        <skinnedMesh geometry={nodes.Pants4.geometry} material={materials.Pants4_skin1} skeleton={nodes.Pants4.skeleton} />
        <skinnedMesh geometry={nodes.Pants5.geometry} material={materials.Pants5_skin1} skeleton={nodes.Pants5.skeleton} />
        <skinnedMesh geometry={nodes.Cap4.geometry} material={materials.Cap4_skin1} skeleton={nodes.Cap4.skeleton} />
        <skinnedMesh geometry={nodes.Cap5.geometry} material={materials.Cap5_6_skin1} skeleton={nodes.Cap5.skeleton} />
        <skinnedMesh geometry={nodes.Cap6.geometry} material={materials.Cap5_6_skin1} skeleton={nodes.Cap6.skeleton} position={[-0.27, 0, 0]} />
        <skinnedMesh geometry={nodes.Cap7.geometry} material={materials.Cap5_6_skin1} skeleton={nodes.Cap7.skeleton} position={[-0.27, 0, 0]} />
        <skinnedMesh geometry={nodes.CHR6_Head.geometry} material={materials.Head6} skeleton={nodes.CHR6_Head.skeleton} />
        <group position={[0, 0.19, 0.76]} rotation={[-0.42, 0, 0]}>
          <skinnedMesh geometry={nodes.Goggles2_up_1.geometry} material={materials.Equip1_skin1} skeleton={nodes.Goggles2_up_1.skeleton} />
          <skinnedMesh geometry={nodes.Goggles2_up_2.geometry} material={materials.Glass_skin1} skeleton={nodes.Goggles2_up_2.skeleton} />
        </group>
        <skinnedMesh geometry={nodes.Headset1.geometry} material={materials.Helmet2_skin1} skeleton={nodes.Headset1.skeleton} />
        <skinnedMesh geometry={nodes.Headset2.geometry} material={materials.Helmet2_skin1} skeleton={nodes.Headset2.skeleton} />
        <skinnedMesh geometry={nodes.Headset3.geometry} material={materials.Helmet2_skin1} skeleton={nodes.Headset3.skeleton} />
        <skinnedMesh geometry={nodes.Helmet1.geometry} material={materials.Cap1_Skin1} skeleton={nodes.Helmet1.skeleton} />
        <skinnedMesh geometry={nodes.Helmet1_Fastering.geometry} material={materials.Cap1_Skin1} skeleton={nodes.Helmet1_Fastering.skeleton} />
        <skinnedMesh geometry={nodes.Helmet1_For_goggles.geometry} material={materials.Cap1_Skin1} skeleton={nodes.Helmet1_For_goggles.skeleton} />
        <skinnedMesh geometry={nodes.Helmet2.geometry} material={materials.Helmet2_skin1} skeleton={nodes.Helmet2.skeleton} />
        <skinnedMesh geometry={nodes.Helmet2_For_goggles.geometry} material={materials.Helmet2_skin1} skeleton={nodes.Helmet2_For_goggles.skeleton} position={[0, 0, 0.12]} rotation={[-0.07, 0, 0]} />
        <skinnedMesh geometry={nodes.Helmet2_fastening.geometry} material={materials.Helmet2_skin1} skeleton={nodes.Helmet2_fastening.skeleton} />
        <skinnedMesh geometry={nodes.Helmet3.geometry} material={materials.Helmet3_skin1} skeleton={nodes.Helmet3.skeleton} />
        <skinnedMesh geometry={nodes.Helmet3_fastering.geometry} material={materials.Helmet3_skin1} skeleton={nodes.Helmet3_fastering.skeleton} />
        <skinnedMesh geometry={nodes.NVG_disabled.geometry} material={materials.Helmet2_skin1} skeleton={nodes.NVG_disabled.skeleton} position={[0, 0, 0.01]} />
        <skinnedMesh geometry={nodes.NVG_enabled.geometry} material={materials.Helmet2_skin1} skeleton={nodes.NVG_enabled.skeleton} position={[0, 0, 0.01]} />

        <skinnedMesh geometry={nodes.Vest1_Belt.geometry} material={materials.Vest1_Skin1} skeleton={nodes.Vest1_Belt.skeleton} />
        <skinnedMesh geometry={nodes.Vest2_Bottom.geometry} material={materials.Vest2_skin1} skeleton={nodes.Vest2_Bottom.skeleton} />
        <skinnedMesh geometry={nodes.Backpack2.geometry} material={materials.Backpack2_skin1} skeleton={nodes.Backpack2.skeleton} />
        <skinnedMesh geometry={nodes.Backpack2_handle.geometry} material={materials.Backpack2_skin1} skeleton={nodes.Backpack2_handle.skeleton} />
        <skinnedMesh geometry={nodes.Backpack3.geometry} material={materials.Backpack3_skin1} skeleton={nodes.Backpack3.skeleton} />
        <skinnedMesh geometry={nodes.BackPack3_handle.geometry} material={materials.Backpack3_skin1} skeleton={nodes.BackPack3_handle.skeleton} />
        <skinnedMesh geometry={nodes.Shirt5.geometry} material={materials.Shirt5_skin1} skeleton={nodes.Shirt5.skeleton} />
        <skinnedMesh geometry={nodes.Vest1.geometry} material={materials.Vest1_Skin1} skeleton={nodes.Vest1.skeleton} />
        <skinnedMesh geometry={nodes.Vest2.geometry} material={materials.Vest2_skin1} skeleton={nodes.Vest2.skeleton} />
        <skinnedMesh geometry={nodes.Vest2_collar.geometry} material={materials.Vest2_skin1} skeleton={nodes.Vest2_collar.skeleton} />
        <skinnedMesh geometry={nodes.Vest2_Shoulder_L.geometry} material={materials.Vest2_skin1} skeleton={nodes.Vest2_Shoulder_L.skeleton} />
        <skinnedMesh geometry={nodes.Vest2_Shoulder_R.geometry} material={materials.Vest2_skin1} skeleton={nodes.Vest2_Shoulder_R.skeleton} />
        <skinnedMesh geometry={nodes.Shirt4.geometry} material={materials.Shirt4_skin1} skeleton={nodes.Shirt4.skeleton} />
        <skinnedMesh geometry={nodes.Shirt6.geometry} material={materials.Shirt6_skin1} skeleton={nodes.Shirt6.skeleton} />
        <skinnedMesh geometry={nodes.CHR_Male_Hands.geometry} material={materials.Hands1_skin1} skeleton={nodes.CHR_Male_Hands.skeleton} />
        <skinnedMesh geometry={nodes.CHR_Male_Palm_hands.geometry} material={materials.Hands1_skin1} skeleton={nodes.CHR_Male_Palm_hands.skeleton} />
        <skinnedMesh geometry={nodes.Outfit1_1.geometry} material={materials.Vest2_skin1} skeleton={nodes.Outfit1_1.skeleton} />
        <skinnedMesh geometry={nodes.Outfit1_2.geometry} material={materials.Equip2_skin1} skeleton={nodes.Outfit1_2.skeleton} />
        <skinnedMesh geometry={nodes.Outfit1_3.geometry} material={materials.Pouches1_Skin1} skeleton={nodes.Outfit1_3.skeleton} />
        <skinnedMesh geometry={nodes.Head_Wire.geometry} material={materials.Equip2_skin1} skeleton={nodes.Head_Wire.skeleton} position={[-0.26, 0.27, 0.03]} rotation={[0, 0, -0.12]} scale={[1, 1.4, 1]} />
        <skinnedMesh geometry={nodes.Radio1.geometry} material={materials.Equip2_skin1} skeleton={nodes.Radio1.skeleton} />
        <skinnedMesh geometry={nodes.Radio2.geometry} material={materials.Equip2_skin1} skeleton={nodes.Radio2.skeleton} />
        <skinnedMesh geometry={nodes.Radio3.geometry} material={materials.Equip2_skin1} skeleton={nodes.Radio3.skeleton} />
        <skinnedMesh geometry={nodes.Radio4.geometry} material={materials.Equip2_skin1} skeleton={nodes.Radio4.skeleton} />
        <skinnedMesh geometry={nodes.Radio5.geometry} material={materials.Equip2_skin1} skeleton={nodes.Radio5.skeleton} />
        <skinnedMesh geometry={nodes.Radio6.geometry} material={materials.Equip2_skin1} skeleton={nodes.Radio6.skeleton} />
        <skinnedMesh geometry={nodes.Radio7.geometry} material={materials.Equip2_skin1} skeleton={nodes.Radio7.skeleton} />
        <skinnedMesh geometry={nodes.Holster1_Pistol__for_Pants2_5__1.geometry} material={materials.Equip2_skin1} skeleton={nodes.Holster1_Pistol__for_Pants2_5__1.skeleton} />
        <skinnedMesh geometry={nodes.Holster1_Pistol__for_Pants2_5__2.geometry} material={materials.Pistol1_skin1} skeleton={nodes.Holster1_Pistol__for_Pants2_5__2.skeleton} />
        <skinnedMesh geometry={nodes.Gasmask2_1.geometry} material={materials.Glass_skin1} skeleton={nodes.Gasmask2_1.skeleton} />
        <skinnedMesh geometry={nodes.Gasmask2_2.geometry} material={materials.Gasmask1_skin1} skeleton={nodes.Gasmask2_2.skeleton} />
        <skinnedMesh geometry={nodes.Goggles1_1.geometry} material={materials.Glass_skin1} skeleton={nodes.Goggles1_1.skeleton} />
        <skinnedMesh geometry={nodes.Goggles1_2.geometry} material={materials.Cap4_skin1} skeleton={nodes.Goggles1_2.skeleton} />
        <skinnedMesh geometry={nodes.Goggles2_for_helmet_1.geometry} material={materials.Equip1_skin1} skeleton={nodes.Goggles2_for_helmet_1.skeleton} />
        <skinnedMesh geometry={nodes.Goggles2_for_helmet_2.geometry} material={materials.Glass_skin1} skeleton={nodes.Goggles2_for_helmet_2.skeleton} />
        <skinnedMesh geometry={nodes.Helmet3_Visor_close_1.geometry} material={materials.Helmet3_skin1} skeleton={nodes.Helmet3_Visor_close_1.skeleton} />
        <skinnedMesh geometry={nodes.Helmet3_Visor_close_2.geometry} material={materials.Glass_skin1} skeleton={nodes.Helmet3_Visor_close_2.skeleton} />
        <skinnedMesh geometry={nodes.Helmet3_Visor_open_1.geometry} material={materials.Helmet3_skin1} skeleton={nodes.Helmet3_Visor_open_1.skeleton} />
        <skinnedMesh geometry={nodes.Helmet3_Visor_open_2.geometry} material={materials.Glass_skin1} skeleton={nodes.Helmet3_Visor_open_2.skeleton} />
        <skinnedMesh geometry={nodes.CHR_Male_Gloves_1.geometry} material={materials.Hands1_skin1} skeleton={nodes.CHR_Male_Gloves_1.skeleton} />
        <skinnedMesh geometry={nodes.CHR_Male_Gloves_2.geometry} material={materials.Equip2_skin1} skeleton={nodes.CHR_Male_Gloves_2.skeleton} />
      </group>
    </group>
  )
}

useGLTF.preload('https://ac-dev-s3.s3.us-west-1.amazonaws.com/glb/characters/fullModels/SK_Military_Character6-full.glb')
