/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./CQBMaster_custom.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function CQBMaster_custom({sight,muzzle}) {
  const { nodes, materials } = useGLTF('https://ac-dev-s3.s3.us-west-1.amazonaws.com/glb/weapons/fullModels/CQBMaster-custom-transformed.glb')
  return (
    <group dispose={null}>
      <group position={[1.22, -2.67, 1.22]} rotation={[-Math.PI, 0.05, -Math.PI]} scale={1.98}>
        <group scale={0.59}>
          <mesh geometry={nodes.Gun1.geometry} material={materials['Material_0.002']} position={[0.16, 0.03, 0.01]} rotation={[0.29, 0.45, 2.59]} scale={0.86}>
            <mesh geometry={nodes.Mesh_0001_1.geometry} material={materials['Material_1.002']} />
            <mesh geometry={nodes.Mesh_0001_2.geometry} material={materials['Material_2.002']} />
            <mesh geometry={nodes.Mesh_0001_3.geometry} material={materials['Material_3.002']} />
            <mesh geometry={nodes.Mesh_0001_4.geometry} material={materials['Material_4.002']} />
            <mesh geometry={nodes.Mesh_0001_5.geometry} material={materials['Material_5.002']} />
            <mesh geometry={nodes.Mesh_0001_6.geometry} material={materials['Material_6.002']} />
            <mesh geometry={nodes.Mesh_0001_7.geometry} material={materials['Material_7.002']} />
            <mesh geometry={nodes.Mesh_0001_8.geometry} material={materials['Material_8.002']} />
            <mesh geometry={nodes.Mesh_0001_9.geometry} material={materials['Material_9.002']} />
            <mesh geometry={nodes.Mesh_0001_10.geometry} material={materials['Material_10.002']} />
            <mesh geometry={nodes.Mesh_0001_11.geometry} material={materials['Material_11.002']} />
            <mesh geometry={nodes.Mesh_0001_12.geometry} material={materials['Material_12.002']} />
            <mesh geometry={nodes.Mesh_0001_13.geometry} material={materials['Material_13.002']} />
            <mesh geometry={nodes.Mesh_0001_14.geometry} material={materials['Material_14.002']} />
            <mesh geometry={nodes.Mesh_0001_15.geometry} material={materials['Material_15.002']} />
            <mesh geometry={nodes.Mesh_0001_16.geometry} material={materials['Material_16.002']} />
            <mesh geometry={nodes.Mesh_0001_17.geometry} material={materials['Material_17.002']} />
            <mesh geometry={nodes.Mesh_0001_18.geometry} material={materials['Material_18.002']} />
            <mesh geometry={nodes.Mesh_0001_19.geometry} material={materials['Material_19.002']} />
            <mesh geometry={nodes.Mesh_0001_20.geometry} material={materials['Material_20.002']} />
            <mesh geometry={nodes.Mesh_0001_21.geometry} material={materials['Material_21.002']} />
            <mesh geometry={nodes.Mesh_0001_22.geometry} material={materials['Material_22.002']} />
            <mesh geometry={nodes.Mesh_0001_23.geometry} material={materials['Material_23.002']} />
            <mesh geometry={nodes.Mesh_0001_24.geometry} material={materials['Material_24.002']} />
            <mesh geometry={nodes.Mesh_0001_25.geometry} material={materials['Material_25.002']} />
          </mesh>
        </group>
        <group scale={0.27}>
          <group position={[-0.64, 0.49, 0]}>
            <mesh visible={muzzle == 'Flash_Light_(1)'} geometry={nodes['Flash_Light_(1)'].geometry} material={materials['Flash Light (1)']} position={[-0.37, -0.38, 0.03]} rotation={[-1.61, 0, -1.49]} scale={[2.84, 2.96, 2.84]} />
          </group>
          <group position={[-1.2, 0.54, -4.6]} scale={0.98}>
            <mesh visible={muzzle == 'Flash_Hider_(1)'} geometry={nodes['Flash_Hider_(1)'].geometry} material={materials.Flash_Hider_1_Material} position={[-0.72, 0.06, 4.71]} rotation={[0, -1.56, 0]} scale={8.57} />
            <mesh visible={muzzle == 'Flash_Hider_(2)'} geometry={nodes['Flash_Hider_(2)'].geometry} material={materials.Flash_Hider_2_Material} position={[-0.8, 0.06, 4.73]} rotation={[0, -1.57, 0]} scale={6.46} />
            <mesh visible={muzzle == 'Flash_Hider_(3)'} geometry={nodes['Flash_Hider_(3)'].geometry} material={materials.Flash_Hider_3_Material} position={[-0.6, 0.06, 4.71]} rotation={[Math.PI, -1.56, Math.PI]} scale={6.65} />
            <mesh visible={muzzle == 'Flash_Hider_(4)'} geometry={nodes['Flash_Hider_(4)'].geometry} material={materials.Flash_Hider_4_Material} position={[-0.64, 0.05, 4.72]} rotation={[0, -1.55, 0]} scale={5.7} />
            <mesh visible={muzzle == 'Suppressor_(1)'} geometry={nodes['Suppressor_(1)'].geometry} material={materials.Suppressor_1_Material} position={[-0.92, 0.07, 4.69]} rotation={[Math.PI, -1.56, Math.PI]} scale={4.64} />
            <mesh visible={muzzle == 'Suppressor_(2)'} geometry={nodes['Suppressor_(2)'].geometry} material={materials.Suppressor_2_Material} position={[-0.9, 0.06, 4.71]} rotation={[0, -1.56, 0]} scale={4.23} />
            <mesh visible={muzzle == 'Suppressor_(3)'} geometry={nodes['Suppressor_(3)'].geometry} material={materials.Suppressor_3_Material} position={[-0.97, 0.06, 4.69]} rotation={[Math.PI, -1.55, Math.PI]} scale={4.23} />
          </group>
          <group position={[1.22, 0.84, 0.02]} scale={0.98}>
            <group visible={sight == 'Reflex_Sight_(2)'} position={[-0.28, 0.05, -0.02]} rotation={[Math.PI, -1.5, Math.PI]} scale={1.94}>
              <mesh geometry={nodes['Reflex_Sight_(2)_1'].geometry} material={materials['Reflex Sight (2) Body']} />
              <mesh geometry={nodes['Reflex_Sight_(2)_2'].geometry} material={materials['Reflex Sight (2) Glass']} />
            </group>
            <group visible={sight == 'Reflex_Sight_(3)'} position={[-0.28, 0.05, -0.02]} rotation={[Math.PI, -1.5, Math.PI]} scale={1.94}>
              <mesh geometry={nodes['Reflex_Sight_(3)_1'].geometry} material={materials['Reflex Sight (3) Body']} />
              <mesh geometry={nodes['Reflex_Sight_(3)_2'].geometry} material={materials['Reflex Sight (3) Glass']} />
            </group>
            <group visible={sight == 'Reflex_Sight_(1)'} position={[-0.28, 0.05, -0.02]} rotation={[Math.PI, -1.5, Math.PI]} scale={1.94}>
              <mesh geometry={nodes['Reflex_Sight_(1)_1'].geometry} material={materials['Reflex Sight (1) Body']} />
              <mesh geometry={nodes['Reflex_Sight_(1)_2'].geometry} material={materials['Reflex Sight (1) Glass']} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('https://ac-dev-s3.s3.us-west-1.amazonaws.com/glb/weapons/fullModels/CQBMaster-custom-transformed.glb')
