/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 SM_Military_Rifle3full.glb --transform
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function SM_Military_Rifle3FullModel(props) {
  const { nodes, materials } = useGLTF('https://ac-dev-s3.s3.us-west-1.amazonaws.com/glb/weapons/fullModels/SM_Military_Rifle3FullModel-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.52, 0.08]} rotation={[0, Math.PI / 2, 0]} scale={103.99}>
        <group scale={0.27}>
          <group position={[-2.73, 0.23, 0]}>
            <mesh geometry={nodes.barrel_base.geometry} material={materials.T_Military_Rifle3} position={[2.32, -0.18, 0]} rotation={[1.57, 0, 3.14]} scale={0.04} />
            <mesh geometry={nodes['Flash_Hider_(1)'].geometry} material={materials['Flash Hider (1)']} position={[-0.05, -0.01, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Flash_Hider_(2)'].geometry} material={materials['Flash Hider (1)']} position={[-0.07, -0.01, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Flash_Hider_(3)'].geometry} material={materials['Flash Hider (1)']} position={[-0.13, -0.01, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Flash_Hider_(4)'].geometry} material={materials['Flash Hider (1)']} position={[-0.29, -0.01, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Muzzle_Break_(1)'].geometry} material={materials['Muzzle Break (1)']} position={[-0.26, -0.01, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Muzzle_Break_(2)'].geometry} material={materials['Muzzle Break (1)']} position={[-0.16, -0.01, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Muzzle_Break_(3)'].geometry} material={materials['Muzzle Break (1)']} position={[-0.21, -0.01, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Suppressor_(1)'].geometry} material={materials['Flash Hider (1)']} position={[-0.1, -0.01, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Suppressor_(2)'].geometry} material={materials['Flash Hider (1)']} position={[-0.51, -0.01, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Suppressor_(3)'].geometry} material={materials['Flash Hider (1)']} position={[-0.32, -0.02, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
          </group>
          <group position={[-1.6, 0.01, 0.02]} scale={0.82}>
            <group position={[0.07, -0.1, -0.02]} rotation={[-1.57, -1.55, -1.57]} scale={0.05}>
              <mesh geometry={nodes.Base.geometry} material={materials['Flash Hider (1)']} position={[0, 4.56, 2.21]} rotation={[0.02, 0, 0]} scale={0.95} />
              <mesh geometry={nodes.Grip.geometry} material={materials['Flash Hider (1)']} position={[-0.08, -0.15, -0.17]} rotation={[0.02, 0, 0]} scale={0.95} />
            </group>
            <mesh geometry={nodes['Angled_Grip_(1)'].geometry} material={materials['Flash Hider (1)']} position={[-0.01, 0.07, -0.03]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Angled_Grip_(2)'].geometry} material={materials['Flash Hider (1)']} position={[0, 0.06, -0.03]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Angled_Grip_(3)'].geometry} material={materials['Flash Hider (1)']} position={[0.05, 0.07, -0.03]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes.Bipod.geometry} material={materials['Flash Hider (1)']} position={[-0.02, -0.28, -0.03]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Vertical_Grip_(1)'].geometry} material={materials['Flash Hider (1)']} position={[0, -0.16, -0.02]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Vertical_Grip_(2)'].geometry} material={materials['Flash Hider (1)']} position={[0, -0.08, -0.03]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Vertical_Grip_(3)'].geometry} material={materials['Flash Hider (1)']} position={[0, 0.07, -0.02]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Vertical_Grip_(4)'].geometry} material={materials['Flash Hider (1)']} position={[0, -0.06, -0.03]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Vertical_Grip_(5)'].geometry} material={materials['Flash Hider (1)']} position={[0, -0.04, -0.03]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Vertical_Grip_(6)'].geometry} material={materials['Flash Hider (1)']} position={[0, 0.07, -0.03]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
          </group>
          <group position={[-0.81, -0.11, 0]}>
            <group position={[0.04, -0.12, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.03}>
              <mesh geometry={nodes.Extended003.geometry} material={materials['Flash Hider (1)']} position={[1.62, 0.02, 2.3]} />
              <mesh geometry={nodes.Standard003.geometry} material={materials['Flash Hider (1)']} position={[1.26, 0, -2.16]} />
            </group>
            <group position={[0.06, -0.14, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.03}>
              <mesh geometry={nodes.Extended004.geometry} material={materials['Flash Hider (1)']} position={[1.46, 0, 3.99]} />
              <mesh geometry={nodes.Short004.geometry} material={materials['Flash Hider (1)']} position={[0.48, 0, -6.64]} />
              <mesh geometry={nodes.Standard004.geometry} material={materials['Flash Hider (1)']} position={[0.58, -0.01, -1.21]} />
            </group>
            <group position={[0.04, -0.17, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.03}>
              <mesh geometry={nodes.Extended001.geometry} material={materials['Flash Hider (1)']} position={[1.18, 0.12, 3.77]} />
              <mesh geometry={nodes.Short001.geometry} material={materials['Flash Hider (1)']} position={[-0.09, -0.02, -7.42]} />
              <mesh geometry={nodes.Standard001.geometry} material={materials['Flash Hider (1)']} position={[0.75, 0.01, 0]} />
            </group>
            <group position={[0.05, -0.12, -0.01]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.03}>
              <mesh geometry={nodes.Extended002.geometry} material={materials['Flash Hider (1)']} position={[2.09, -0.11, -0.06]} />
              <mesh geometry={nodes.Short002.geometry} material={materials['Flash Hider (1)']} position={[0.23, 0, -7.38]} />
              <mesh geometry={nodes.Standard002.geometry} material={materials['Flash Hider (1)']} position={[0.63, -0.03, -3.38]} />
            </group>
            <group position={[0.03, -0.14, 0]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={0.03}>
              <mesh geometry={nodes.Extended.geometry} material={materials['Flash Hider (1)']} position={[2.67, 0, 4.26]} />
              <mesh geometry={nodes.Short.geometry} material={materials['Flash Hider (1)']} position={[0.59, 0, -5.45]} />
              <mesh geometry={nodes.Standard.geometry} material={materials['Flash Hider (1)']} position={[2.11, 0, 0.29]} />
            </group>
            <mesh geometry={nodes.base_magazine.geometry} material={materials.T_Military_Rifle3} position={[0.41, 0.16, 0]} rotation={[1.57, 0, 3.14]} scale={0.04} />
            <mesh geometry={nodes.Box_Magazine.geometry} material={materials['Flash Hider (1)']} position={[0.02, 0.01, 0.01]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Drum_Magazine_(1)'].geometry} material={materials['Flash Hider (1)']} position={[0.01, -0.1, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Drum_Magazine_(2)'].geometry} material={materials['Flash Hider (1)']} position={[0.03, -0.2, -0.01]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Drum_Magazine_(3)'].geometry} material={materials['Flash Hider (1)']} position={[-0.05, -0.17, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Drum_Magazine_(4)'].geometry} material={materials['Flash Hider (1)']} position={[0.03, -0.06, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
          </group>
          <group position={[-2.05, 0.18, 0]} scale={0.49}>
            <mesh geometry={nodes['Flash_Light_(1)'].geometry} material={materials['Flash Hider (1)']} position={[-0.01, -0.06, 0.01]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Flash_Light_(2)'].geometry} material={materials['Flash Hider (1)']} position={[-0.03, -0.08, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes.FlashLaser_Combo.geometry} material={materials['Flash Hider (1)']} position={[-0.02, -0.09, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Laser_Sight_(1)'].geometry} material={materials['Flash Hider (1)']} position={[-0.04, -0.07, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
            <mesh geometry={nodes['Laser_Sight_(2)'].geometry} material={materials['Flash Hider (1)']} position={[-0.09, -0.1, 0.01]} rotation={[0, -Math.PI / 2, 0]} scale={0.04} />
          </group>
          <group position={[-0.57, 0.43, 0.02]} scale={0.91}>
            <group position={[0.48, 0.06, -0.01]} rotation={[Math.PI / 2, 0.08, Math.PI / 2]} scale={0.01}>
              <mesh geometry={nodes.Magnifier_Mount.geometry} material={materials['Flash Hider (1)']} position={[2.12, 31.66, 2.73]} />
              <group position={[-1.27, 39.53, -5.61]}>
                <mesh geometry={nodes.Mesh066.geometry} material={materials['Flash Hider (1)']} />
                <mesh geometry={nodes.Mesh066_1.geometry} material={materials['Flash Hider (1)']} />
              </group>
            </group>
            <group position={[-0.05, 0.03, -0.03]} rotation={[0, -Math.PI / 2, 0]} scale={0.04}>
              <mesh geometry={nodes.Mesh077.geometry} material={materials['Flash Hider (1)']} />
              <mesh geometry={nodes.Mesh077_1.geometry} material={materials['Flash Hider (1)']} />
            </group>
            <group position={[-0.03, 0.09, -0.01]} rotation={[0, -Math.PI / 2, 0]} scale={0.04}>
              <mesh geometry={nodes.Mesh075.geometry} material={materials['Flash Hider (1)']} />
              <mesh geometry={nodes.Mesh075_1.geometry} material={materials['Flash Hider (1)']} />
            </group>
            <group position={[-0.06, 0.1, -0.02]} rotation={[0, -Math.PI / 2, 0]} scale={0.04}>
              <mesh geometry={nodes.Mesh073.geometry} material={materials['Flash Hider (1)']} />
              <mesh geometry={nodes.Mesh073_1.geometry} material={materials['Flash Hider (1)']} />
            </group>
            <group position={[0, 0.05, -0.02]} rotation={[0, -Math.PI / 2, 0]} scale={0.04}>
              <mesh geometry={nodes.Mesh071.geometry} material={materials['Flash Hider (1)']} />
              <mesh geometry={nodes.Mesh071_1.geometry} material={materials['Flash Hider (1)']} />
            </group>
            <group position={[0.01, 0.03, -0.01]} rotation={[0, -Math.PI / 2, 0]} scale={0.04}>
              <mesh geometry={nodes.Mesh076.geometry} material={materials['Flash Hider (1)']} />
              <mesh geometry={nodes.Mesh076_1.geometry} material={materials['Flash Hider (1)']} />
            </group>
            <group position={[-0.03, 0.01, -0.01]} rotation={[0, -Math.PI / 2, 0]} scale={0.04}>
              <mesh geometry={nodes.Mesh070.geometry} material={materials['Flash Hider (1)']} />
              <mesh geometry={nodes.Mesh070_1.geometry} material={materials['Flash Hider (1)']} />
            </group>
            <group position={[0.01, 0.01, -0.01]} rotation={[0, -Math.PI / 2, 0]} scale={0.04}>
              <mesh geometry={nodes.Mesh069.geometry} material={materials['Flash Hider (1)']} />
              <mesh geometry={nodes.Mesh069_1.geometry} material={materials['Flash Hider (1)']} />
            </group>
            <group position={[0.03, 0.07, -0.01]} rotation={[0, -Math.PI / 2, 0]} scale={0.04}>
              <mesh geometry={nodes.Mesh074.geometry} material={materials['Flash Hider (1)']} />
              <mesh geometry={nodes.Mesh074_1.geometry} material={materials['Flash Hider (1)']} />
            </group>
            <group position={[-0.02, 0.06, -0.04]} rotation={[0, -Math.PI / 2, 0]} scale={0.04}>
              <mesh geometry={nodes.Mesh072.geometry} material={materials['Flash Hider (1)']} />
              <mesh geometry={nodes.Mesh072_1.geometry} material={materials['Flash Hider (1)']} />
            </group>
            <group position={[0.02, 0.04, 0]} rotation={[0, -Math.PI / 2, 0]} scale={0.04}>
              <mesh geometry={nodes.Mesh068.geometry} material={materials['Flash Hider (1)']} />
              <mesh geometry={nodes.Mesh068_1.geometry} material={materials['Flash Hider (1)']} />
            </group>
          </group>
        </group>
        <mesh geometry={nodes.Rifle3.geometry} material={materials.T_Military_Rifle3} position={[-0.11, 0.01, 0]} rotation={[1.57, 0, 3.14]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('https://ac-dev-s3.s3.us-west-1.amazonaws.com/glb/weapons/fullModels/SM_Military_Rifle3FullModel-transformed.glb')
